import 'package:flutter/material.dart';
import '../models/complaint.dart';
import '../models/category.dart';
import '../services/api_service.dart';

class ComplaintFormScreen extends StatefulWidget {
  final Complaint? complaint;

  const ComplaintFormScreen({super.key, this.complaint});

  @override
  _ComplaintFormScreenState createState() => _ComplaintFormScreenState();
}

class _ComplaintFormScreenState extends State<ComplaintFormScreen> {
  final _formKey = GlobalKey<FormState>();
  final ApiService _apiService = ApiService();

  late TextEditingController _titleController;
  late TextEditingController _descriptionController;
  String? _selectedCategoryId;
  String _status = 'Pending';
  
  List<Category> _categories = [];
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    _titleController = TextEditingController(text: widget.complaint?.title ?? '');
    _descriptionController = TextEditingController(text: widget.complaint?.description ?? '');
    _selectedCategoryId = widget.complaint?.categoryId;
    _status = widget.complaint?.status ?? 'Pending';
    _fetchCategories();
  }

  void _fetchCategories() async {
    try {
      final categories = await _apiService.getCategories();
      setState(() {
        _categories = categories;
        // Ensure selected category still exists or default to first
        if (_selectedCategoryId == null && _categories.isNotEmpty) {
           // Don't auto select for new complaints to force user choice if we want, 
           // or maybe just leave null.
        }
      });
    } catch (e) {
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(content: Text('Failed to load categories: $e')),
      );
    }
  }

  @override
  void dispose() {
    _titleController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  void _saveComplaint() async {
    if (_formKey.currentState!.validate()) {
      if (_selectedCategoryId == null) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Please select a category')),
        );
        return;
      }

      setState(() => _isLoading = true);

      try {
        if (widget.complaint == null) {
          // Create
          final newComplaint = Complaint(
            id: '', // Generated by backend
            title: _titleController.text,
            description: _descriptionController.text,
            status: _status,
            dateSubmitted: DateTime.now(),
            categoryId: _selectedCategoryId!,
          );
          await _apiService.createComplaint(newComplaint);
        } else {
          // Update
          final updates = {
            'title': _titleController.text,
            'description': _descriptionController.text,
            'status': _status,
            'categoryId': _selectedCategoryId,
          };
          await _apiService.updateComplaint(widget.complaint!.id, updates);
        }
        if (mounted) {
            Navigator.pop(context);
        }
      } catch (e) {
        if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
                SnackBar(content: Text('Failed to save complaint: $e')),
            );
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.complaint == null ? 'New Complaint' : 'Edit Complaint'),
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : Padding(
              padding: const EdgeInsets.all(16.0),
              child: Form(
                key: _formKey,
                child: ListView(
                  children: [
                    TextFormField(
                      controller: _titleController,
                      decoration: const InputDecoration(
                        labelText: 'Title',
                        border: OutlineInputBorder(),
                      ),
                      validator: (value) => value == null || value.isEmpty ? 'Please enter a title' : null,
                    ),
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _descriptionController,
                      decoration: const InputDecoration(
                        labelText: 'Description',
                        border: OutlineInputBorder(),
                      ),
                      maxLines: 3,
                      validator: (value) => value == null || value.isEmpty ? 'Please enter a description' : null,
                    ),
                    const SizedBox(height: 16),
                    DropdownButtonFormField<String>(
                      value: _selectedCategoryId,
                      decoration: const InputDecoration(
                        labelText: 'Category',
                        border: OutlineInputBorder(),
                      ),
                      items: _categories.map((category) {
                        return DropdownMenuItem(
                          value: category.id,
                          child: Text(category.name),
                        );
                      }).toList(),
                      onChanged: (value) => setState(() => _selectedCategoryId = value),
                      validator: (value) => value == null ? 'Please select a category' : null,
                    ),
                    const SizedBox(height: 16),
                    if (widget.complaint != null)
                      DropdownButtonFormField<String>(
                        value: _status,
                        decoration: const InputDecoration(
                          labelText: 'Status',
                          border: OutlineInputBorder(),
                        ),
                        items: ['Pending', 'Resolved'].map((status) {
                          return DropdownMenuItem(
                            value: status,
                            child: Text(status),
                          );
                        }).toList(),
                        onChanged: (value) => setState(() => _status = value!),
                      ),
                    const SizedBox(height: 24),
                    ElevatedButton(
                      onPressed: _saveComplaint,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: Text(widget.complaint == null ? 'Submit Complaint' : 'Update Complaint'),
                    ),
                  ],
                ),
              ),
            ),
    );
  }
}
